var mainContainer = document.querySelector("#mainContainer");
var balanceContainer = document.querySelector(".balanceContainer");
var userBalance = 0;
var userBalanceButton = document.createElement("button");
userBalanceButton.classList.add("userBalanceButton");
userBalanceButton.textContent = "Current Balance: ".concat(userBalance);
balanceContainer.appendChild(userBalanceButton);
var gameplayPlace = document.createElement("div");
gameplayPlace.classList.add("gameplayPlace");
mainContainer.appendChild(gameplayPlace);
var mainPlayIconsContainer = document.createElement("div");
mainPlayIconsContainer.classList.add("mainPlayIconsContainer");
gameplayPlace.appendChild(mainPlayIconsContainer);
var playIconLeft = document.createElement("div");
playIconLeft.classList.add("playIconLeft");
playIconLeft.classList.add("playIcon");
mainPlayIconsContainer.appendChild(playIconLeft);
var playIconCenter = document.createElement("div");
playIconCenter.classList.add("playIconCenter");
playIconCenter.classList.add("playIcon");
mainPlayIconsContainer.appendChild(playIconCenter);
var playIconRight = document.createElement("div");
playIconRight.classList.add("playIconRight");
playIconRight.classList.add("playIcon");
mainPlayIconsContainer.appendChild(playIconRight);
var playButtonContainer = document.createElement("div");
playButtonContainer.classList.add("playButtonContainer");
mainContainer.appendChild(playButtonContainer);
var playButton = document.createElement("button");
playButton.classList.add("playButton");
playButton.textContent = "ROLL";
playButtonContainer.appendChild(playButton);
